# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MatSplit <- function(A, B, splitind) {
    .Call('BeQTLR_MatSplit', PACKAGE = 'BeQTLR', A, B, splitind)
}

RMSE <- function(TrainCor, TestCor, dim) {
    .Call('BeQTLR_RMSE', PACKAGE = 'BeQTLR', TrainCor, TestCor, dim)
}

MAD <- function(TrainCor, TestCor, isMedian, dim) {
    .Call('BeQTLR_MAD', PACKAGE = 'BeQTLR', TrainCor, TestCor, isMedian, dim)
}

PointCor <- function(A, B) {
    .Call('BeQTLR_PointCor', PACKAGE = 'BeQTLR', A, B)
}

GenBoot <- function(samplesize, bootstrapnumber) {
    .Call('BeQTLR_GenBoot', PACKAGE = 'BeQTLR', samplesize, bootstrapnumber)
}

BeQTL <- function(A, B, Bootmat) {
    .Call('BeQTLR_BeQTL', PACKAGE = 'BeQTLR', A, B, Bootmat)
}

Ind <- function(nrow, ind) {
    .Call('BeQTLR_Ind', PACKAGE = 'BeQTLR', nrow, ind)
}

Nind <- function(inpmat, rowindex, colindex) {
    .Call('BeQTLR_Nind', PACKAGE = 'BeQTLR', inpmat, rowindex, colindex)
}

SumRes <- function(cormat, errmat, SnpDF, Genedf, samplesize, tcutoff) {
    .Call('BeQTLR_SumRes', PACKAGE = 'BeQTLR', cormat, errmat, SnpDF, Genedf, samplesize, tcutoff)
}

