# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

MatSplit <- function(A, B, splitind) {
    .Call('BeQTLR_MatSplit', PACKAGE = 'BeQTLR', A, B, splitind)
}

RMSE <- function(TrainCor, TestCor, dim) {
    .Call('BeQTLR_RMSE', PACKAGE = 'BeQTLR', TrainCor, TestCor, dim)
}

MAD <- function(TrainCor, TestCor, isMedian) {
    .Call('BeQTLR_MAD', PACKAGE = 'BeQTLR', TrainCor, TestCor, isMedian)
}

PointCor <- function(A, B) {
    .Call('BeQTLR_PointCor', PACKAGE = 'BeQTLR', A, B)
}

GenBoot <- function(samplesize, bootstrapnumber) {
    .Call('BeQTLR_GenBoot', PACKAGE = 'BeQTLR', samplesize, bootstrapnumber)
}

BeQTL <- function(A, B, Bootmat) {
    .Call('BeQTLR_BeQTL', PACKAGE = 'BeQTLR', A, B, Bootmat)
}

